[project]
name = "aidenadzich-calculator-app"
version = "0.1.0"
description = "Aiden Adzichs Lab01 for ITAS276"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
